"use client";

import { useMemo, useState, type FormEvent } from "react";
import Link from "next/link";
import { AppShell, Brand, ChatShell, PublicShell, type NavItem } from "@/components/shells";
import { Icon } from "@/components/ui/icon";
import { Badge, Button, Card, Checkbox, Chip, EmptyState, IconButton, Notice, SelectField, Skeleton, Switch, TextArea, TextField } from "@/components/ui/primitives";
import { Overlay } from "@/components/ui/overlay";
import { createMockAdapter, type MockScenario } from "@/lib/mock/adapter";
import type { Language, PublicCharacter, TransportState } from "@/lib/contracts";
import { formatNaira } from "@/lib/format";
import { previewSeed } from "./fixtures";
import "./preview.css";

type View = "foundation" | "public" | "user" | "chat" | "admin";
const palette = [ ["Mist", "#FAF8FA"], ["White", "#FFFFFF"], ["Charcoal plum", "#241C23"], ["Muted grape", "#716570"], ["Deep plum", "#682447"], ["Rose wash", "#F5EAF0"] ];
export default function Preview() {
  const [view, setView] = useState<View>("foundation");
  const [destination, setDestination] = useState("Discover");
  const [dialog, setDialog] = useState(false); const [sheet, setSheet] = useState(false);
  const [requests, setRequests] = useState(true); const [selected, setSelected] = useState("All");
  const [name, setName] = useState(""); const [nameError, setNameError] = useState("");
  const [language, setLanguage] = useState<Language>("english");
  const [saving, setSaving] = useState(false); const [feedback, setFeedback] = useState("");
  const [scenario, setScenario] = useState<MockScenario>("ready");
  const [actor, setActor] = useState("demo-user-a");
  const [result, setResult] = useState<TransportState<PublicCharacter[]>>({ status: "idle" });
  const adapter = useMemo(() => createMockAdapter(previewSeed, { actorId: actor === "signed-out" ? null : actor, scenario, latencyMs: 650 }), [actor, scenario]);
  const controls = <div className="lab-toolbar"><Link href="/" className="lab-back"><Icon name="back" /><span className="sr-only">Back to </span>TalkingStage</Link><nav aria-label="Preview layouts" className="row">{([ ["foundation", "Components"], ["public", "Public"], ["user", "User"], ["chat", "Chat"], ["admin", "Admin"] ] as [View, string][]).map(([value, label]) => <button key={value} type="button" className="lab-view-button" aria-pressed={view === value} onClick={() => { setView(value); setDestination(value === "admin" ? "Overview" : "Discover"); }}>{label}</button>)}</nav><Badge tone="neutral">Development only</Badge></div>;
  const returnAction = <Button variant="quiet" onClick={() => setView("foundation")}>Back to components</Button>;
  const shellContent = <div className="stack"><div><p className="supporting muted">Layout preview · mock content</p><h1 className="display page-title" style={{ marginTop: 8 }}>{destination}</h1></div><Card><EmptyState title={destination === "Messages" ? "Your conversations start here" : `${destination} layout`} icon={destination === "Messages" ? "message" : "discover"} action={returnAction}>This preview demonstrates the shell. Full product screens are built in the next stages.</EmptyState></Card><Notice title="Fictional AI experience">All characters and conversations are fictional. This is a development preview.</Notice></div>;
  const userItems: NavItem[] = ([ ["Discover", "discover"], ["Messages", "message"], ["Settings", "settings"] ] as const).map(([label, icon]) => ({ label, icon, active: destination === label, onSelect: () => setDestination(label) }));
  const adminItems: NavItem[] = ([ ["Overview", "discover"], ["Cast", "people"], ["Assets", "photo"], ["Reports", "shield"], ["Payments", "payment"], ["Operations", "settings"], ["Audit", "info"] ] as const).map(([label, icon]) => ({ label, icon, active: destination === label, onSelect: () => setDestination(label) }));

  async function submitName(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setFeedback("");
    if (!name.trim() || name.trim().length > 60) { setNameError("Enter a name between 1 and 60 characters."); return; }
    setNameError(""); setSaving(true);
    const current = await adapter.getCurrentUser();
    if (current.error) { setFeedback(current.error.message); setSaving(false); return; }
    const response = await adapter.updatePreferences({ displayName: name, preferences: { ...current.data.preferences, language }, expectedVersion: current.data.version });
    setSaving(false); setFeedback(response.error ? response.error.message : `Preferences saved for ${response.data.displayName}.`);
  }
  async function loadCharacters() {
    setResult({ status: "pending" });
    const response = await adapter.listCharacters();
    setResult(response.error ? { status: "failed", error: response.error } : { status: "succeeded", data: response.data.items });
  }

  if (view !== "foundation") return <div className="lab-shell-mode">{controls}{view === "public" ? <PublicShell actions={returnAction} footer={<p className="supporting muted">Public footer · adults 18+ · fictional AI characters</p>}>{shellContent}</PublicShell> : view === "chat" ? <ChatShell back={<IconButton icon="back" label="Back to components" onClick={() => setView("foundation")} />} identity={<><strong>Amara, 28</strong><p className="caption muted">Fictional AI character · scripted preview</p></>} actions={<Badge>AI</Badge>} composer={<div className="row"><div style={{ flex: 1, minWidth: 0 }}><TextField label="Message composer preview" placeholder="Write a message…" disabled /></div><IconButton icon="arrow" label="Send unavailable in shell preview" disabled /></div>}><div className="lab-message">What song should I listen to before I decide whether your taste is respectable?</div><p className="caption muted" style={{ marginTop: 8 }}>Scripted sample · no live AI</p></ChatShell> : <AppShell admin={view === "admin"} items={view === "admin" ? adminItems : userItems} actions={<Badge tone="neutral">Mock {view === "admin" ? "admin" : "account"}</Badge>}>{shellContent}</AppShell>}</div>;

  return <div className="lab">{controls}<header className="lab-header container"><Brand /><p className="supporting muted">Design foundations · v0.1</p></header><main id="main-content" className="container lab-main">
    <div className="lab-intro"><div><p className="lab-eyebrow">TalkingStage / The design system</p><h1 className="display">Made for<br /><span>good chemistry.</span></h1><p className="muted lab-intro__copy">A quiet interface. A distinct personality. The building blocks for a more familiar kind of conversation.</p></div><div className="lab-clue"><span className="lab-clue__quote" aria-hidden="true">“</span><blockquote className="display">Good music is a very good opening line.</blockquote><div className="row"><span className="lab-avatar" aria-hidden="true">A</span><div><strong className="supporting">Amara, 28</strong><p className="caption muted">Draft fictional AI character</p></div></div><span className="caption muted">Conversation clue · our signature detail</span></div></div>

    <section className="lab-section" aria-labelledby="colour-title"><div className="lab-section__heading"><div><h2 id="colour-title">Colour with a little feeling.</h2><p className="muted supporting">Plum for action. Rose for emphasis. Space for everything else.</p></div><Badge tone="neutral">Light mode</Badge></div><div className="lab-palette">{palette.map(([label, hex]) => <div key={label} className="lab-swatch"><div className="lab-swatch__colour" style={{ background: hex }} /><strong className="supporting">{label}</strong><span className="caption muted tabular">{hex}</span></div>)}</div></section>

    <section className="lab-section" aria-labelledby="type-title"><div className="lab-section__heading"><div><h2 id="type-title">Personality in the details.</h2><p className="muted supporting">Expressive headings. An interface that gets out of the way.</p></div></div><div className="lab-grid"><Card><p className="caption muted">DM Serif Display · headings</p><p className="display lab-type-sample">A good first impression.</p><p className="supporting muted">Reserved for introductions, page titles, and character names.</p></Card><Card><p className="caption muted">Manrope · interface and conversation</p><p className="lab-body-sample">Tell me one small thing you noticed today.</p><div className="row"><Badge>Fictional AI character</Badge><span className="tabular supporting">{formatNaira(500000)}</span></div><p className="caption muted" style={{ marginTop: 16 }}>16 / 24 body · 14 / 20 supporting · 12 / 16 captions</p></Card></div></section>

    <section className="lab-section" aria-labelledby="actions-title"><div className="lab-section__heading"><div><h2 id="actions-title">One clear next step.</h2><p className="muted supporting">Touch-friendly controls with quieter alternatives.</p></div></div><Card><div className="row"><Button onClick={() => setFeedback("Primary action selected in preview.")}>Shoot your shot <Icon name="arrow" /></Button><Button variant="secondary" onClick={() => setFeedback("Secondary action selected in preview.")}>View profile</Button><Button variant="quiet" onClick={() => setFeedback("No action taken.")}>Not now</Button><IconButton icon="filter" label="Open filters" onClick={() => setSheet(true)} /></div><div className="row" style={{ marginTop: 20 }}><Button loading>Saving changes</Button><Button disabled>Unavailable</Button><Button variant="danger" onClick={() => setDialog(true)}>Reset conversation</Button></div><div className="row" style={{ marginTop: 24 }}><Badge>AI character</Badge><Badge tone="success">Verified payment</Badge><Badge tone="warning">Pending</Badge><Badge tone="danger">Failed</Badge><Badge tone="neutral">Draft</Badge></div></Card></section>

    <section className="lab-section" aria-labelledby="forms-title"><div className="lab-section__heading"><div><h2 id="forms-title">Choices that stay yours.</h2><p className="muted supporting">Visible labels, honest feedback, and consent you control.</p></div></div><div className="lab-grid"><Card><form className="stack" noValidate onSubmit={submitName}><TextField label="Preferred name" value={name} onChange={(event) => setName(event.target.value)} placeholder="What should we call you?" hint="This is how characters address you." error={nameError} autoComplete="off" maxLength={60} /><SelectField label="Conversation language" value={language} onChange={(event) => setLanguage(event.target.value as Language)}><option value="english">English</option><option value="english_pidgin">English with Pidgin</option></SelectField><TextArea label="Example introduction" placeholder="Start with something about you…" hint="Component example only; this text is not sent or stored." /><Button type="submit" loading={saving}>Save preferences</Button></form></Card><Card className="stack"><Switch label="Allow monetary requests" hint="You can decline or turn requests off at any time." checked={requests} onChange={(event) => setRequests(event.target.checked)} /><Notice title={requests ? "Requests are optional" : "Monetary requests are off"}>{requests ? "A payment never buys affection or changes a character’s boundaries." : "Turning requests off does not change conversation warmth."}</Notice><Checkbox label="I understand these are fictional AI characters." /><div><p className="field__label" style={{ marginBottom: 12 }}>Character preference</p><div className="row">{["All", "Women", "Men"].map((label) => <Chip key={label} selected={selected === label} onClick={() => setSelected(label)}>{label}</Chip>)}</div></div><TextField label="Disabled input example" value="Read-only preview" disabled readOnly /></Card></div></section>

    <section className="lab-section" aria-labelledby="states-title"><div className="lab-section__heading"><div><h2 id="states-title">Designed beyond the happy path.</h2><p className="muted supporting">Clear explanations when something is pending, missing, or interrupted.</p></div></div><div className="lab-grid"><div className="stack"><Notice title="Fictional AI experience">Characters are created for entertainment, not real-world meetings.</Notice><Notice title="Payment pending" tone="warning">We’re waiting for payment confirmation.</Notice><Notice title="Your message wasn't sent" tone="danger">Reconnect, then retry the same message.</Notice><Notice title="Preferences saved" tone="success">Your choices are ready for your next conversation.</Notice></div><Card><EmptyState title="Your conversations start here" action={<Button variant="secondary" onClick={() => setView("user")}>Preview navigation</Button>}>Discover a character and introduce yourself.</EmptyState><div aria-label="Loading component example" role="status" className="stack" style={{ paddingTop: 24, borderTop: "1px solid var(--border)" }}><span className="sr-only">Loading preview</span><Skeleton width="40%" height={24} /><Skeleton /><Skeleton width="70%" /></div></Card></div></section>

    <section className="lab-section" aria-labelledby="mock-title"><div className="lab-section__heading"><div><h2 id="mock-title">A foundation ready for real flows.</h2><p className="muted supporting">Typed local adapters. Disposable fixture data. No connected services.</p></div><Badge tone="neutral">Synthetic data</Badge></div><Card><div className="lab-mock-controls"><SelectField label="Mock response" disabled={result.status === "pending" || saving} value={scenario} onChange={(event) => { setScenario(event.target.value as MockScenario); setResult({ status: "idle" }); }}><option value="ready">Ready</option><option value="empty">Empty</option><option value="offline">Offline</option><option value="error">Service error</option></SelectField><SelectField label="Mock account" disabled={result.status === "pending" || saving} value={actor} onChange={(event) => { setActor(event.target.value); setResult({ status: "idle" }); }}><option value="demo-user-a">Demo user A</option><option value="demo-user-b">Demo user B</option><option value="signed-out">Signed out</option></SelectField><Button loading={result.status === "pending"} onClick={loadCharacters}>Load characters</Button><Button variant="quiet" onClick={() => { adapter.reset(); setResult({ status: "idle" }); setFeedback(""); setName(""); setNameError(""); }}>Reset mock data</Button></div><div className="lab-results" aria-live="polite">{result.status === "idle" && <p className="muted supporting">Choose a scenario and load the provisional cast.</p>}{result.status === "pending" && <div className="stack"><Skeleton width="50%" /><Skeleton width="80%" /></div>}{result.status === "failed" && <Notice title={result.error.message} tone="danger">{result.error.retryable ? "Change the mock response to Ready, then retry." : "Choose a signed-in demo account to continue."}</Notice>}{result.status === "succeeded" && (result.data.length ? <div className="lab-character-list">{result.data.map((character) => <div key={character.id} className="lab-character"><span className="lab-avatar" aria-hidden="true">{character.name[0]}</span><div><strong className="supporting">{character.name}, {character.age}</strong><p className="caption muted">{character.fictionalLocation} · Fictional AI character</p><p className="supporting lab-character__clue">“{character.conversationClue}”</p></div></div>)}</div> : <EmptyState title="No characters to show" icon="discover">Switch the mock response to Ready to see the draft cast.</EmptyState>)}</div></Card></section>

    <footer className="lab-footer supporting muted"><p>Stage 1 foundations. Images and profiles remain subject to approval.</p><p>No authentication, AI, storage, or payment provider is connected.</p></footer>
  </main>{feedback && <div className="lab-feedback" role="status"><span>{feedback}</span><IconButton icon="close" label="Dismiss feedback" onClick={() => setFeedback("")} /></div>}
  <Overlay open={dialog} onClose={() => setDialog(false)} title="Reset this conversation?" description="Confirmation pattern only. No conversation is changed in this component preview." footer={<><Button variant="secondary" onClick={() => setDialog(false)}>Keep conversation</Button><Button variant="danger" onClick={() => { setDialog(false); setFeedback("Reset pattern confirmed. No conversation data was changed."); }}>Reset conversation</Button></>}><Notice title="Make the consequences clear">A product reset must explain whether saved memories are kept or removed.</Notice></Overlay>
  <Overlay open={sheet} onClose={() => setSheet(false)} sheet title="Character filters" description="Bottom sheet on mobile; centred dialog on larger screens." footer={<><Button variant="quiet" onClick={() => setSelected("All")}>Reset filters</Button><Button onClick={() => { setSheet(false); setFeedback(`Filter selected: ${selected}.`); }}>Apply filters</Button></>}><div className="row">{["All", "Women", "Men"].map((label) => <Chip key={label} selected={selected === label} onClick={() => setSelected(label)}>{label}</Chip>)}</div></Overlay>
  </div>;
}
