import Link from "next/link";
import { PublicShell } from "./shells";
import { Notice } from "./ui/primitives";
export type InformationKind = "terms" | "privacy" | "payment-information" | "support";
const content: Record<InformationKind, { title: string; introduction: string; sections: [string, string][] }> = {
  terms: { title: "A clear understanding.", introduction: "TalkingStage is an entertainment experience with fictional AI characters for adults aged 18 and over.", sections: [["What the experience offers", "Browse operator-created fictional characters and continue private text conversations. Characters are not real people, do not receive your money, and cannot arrange real-world meetings."], ["Respect and boundaries", "The launch experience is non-explicit. A character's boundaries and romantic pace are not changed by payments. You can report messages, images, and characters."], ["Before public launch", "Final service terms, operator identity, governing provisions, eligibility details, and dispute/support procedures still require review. This page is a draft layout, not final contractual terms."]] },
  privacy: { title: "Your conversations. Your choices.", introduction: "Privacy controls should make it clear what is saved and what you can remove.", sections: [["Chats and memory", "The planned product keeps conversations private to their owner and authorised operational processes. You can inspect, disable, and remove saved memories. Prototype data in this build does not establish production privacy or security."], ["Deletion and retention", "You can review account deletion in Settings. Deleting or resetting a conversation keeps memories by default, with an explicit option to clear that character’s memories; payment history remains. Real retention periods, backup expiry and necessary transaction-record exceptions still require policy review."], ["This frontend preview", "Disposable onboarding, synthetic memory, conversation and simulated payment/report metadata use your browser’s session storage. Custom chat text and report details are replaced by placeholders in stored fixtures. Email addresses and passwords are not saved there. Use sample information only. Signing out ends demo access; deleting the demo account clears these disposable fixtures."], ["Before public launch", "The data controller, lawful processing details, service providers, retention schedule, rights/contact procedures, and final policy text require review."]] },
  "payment-information": { title: "Optional means optional.", introduction: "A monetary gift is voluntary support received by TalkingStage's operator and associated with a fictional character.", sections: [["Who receives a payment", "A character is fictional and has no bank account. The business operator receives payments through the selected gateway. Final merchant identity and checkout details will be disclosed before launch."], ["Your choice, every time", "You can decline, ignore, or disable monetary requests. A payment does not buy an item, guarantee a romantic response, or change boundaries. No recurring or saved-card charging is assumed."], ["Confirm, then checkout", "An explicit amount and NGN currency confirmation comes before a backend-created checkout link. Only server-verified gateway results confirm success. No payment can be made in this frontend preview."], ["Policies still required", "The gateway, amount limits, request cooldowns, refund/dispute process, and payment-record retention policy remain pending."]] },
  support: { title: "Help should be easy to find.", introduction: "The production support channel is still being selected. This preview does not submit support requests.", sections: [["Account access", "Use the recovery flow to review how access recovery will work. No email is sent by this demo."], ["Reports and payments", "Use Report on a message, character photo or profile to review reporting. Reports and payment history are simulated in this preview. No report reaches a real moderation team and no money moves. A payment screenshot or checkout redirect is not proof of payment; production success requires a verified result."], ["Before public launch", "An operator support contact, response expectations, escalation procedures, and refund/dispute guidance must be published. No fictional support email or phone number has been supplied here."]] },
};
export function InformationPage({ kind }: { kind: InformationKind }) {
  const page = content[kind];
  return <PublicShell actions={<Link href="/sign-in" className="button button--quiet">Sign in</Link>} footer={<nav className="row supporting" aria-label="Information pages"><Link href="/terms">Terms</Link><Link href="/privacy">Privacy</Link><Link href="/payment-information">Payments</Link><Link href="/support">Support</Link></nav>}><article className="information-page stack"><Link href="/">Back to home</Link><p className="supporting muted">TalkingStage · Draft information</p><h1 className="display page-title">{page.title}</h1><p className="muted">{page.introduction}</p><Notice title="Draft for product review" tone="warning">This content is provisional and must be completed and reviewed before public launch.</Notice>{page.sections.map(([heading, body]) => <section key={heading} className="stack"><h2>{heading}</h2><p className="muted">{body}</p></section>)}{kind === "support" && <Link href="/recover" className="button button--secondary">Review account recovery</Link>}</article></PublicShell>;
}
