"use client";
import Link from 'next/link';
import { useRef, useState } from 'react';
import type { PaymentIntent, PaymentStatus } from '@/lib/contracts';
import { confirmGift, createGift, loadSpace, paymentById, paymentHistory, reviewPaymentStatus, simulateCheckout, type SpaceScenario } from '@/lib/mock/personal-space';
import { characters, readConversation } from '@/lib/mock/discovery';
import { formatNaira, parseNaira } from '@/lib/format';
import { SpaceBack, SpacePage, SpaceReview, usePersonalSpace } from './personal-space';
import { Badge, Button, EmptyState, Notice, SelectField, Skeleton, TextField } from './ui/primitives';
import { Overlay } from './ui/overlay';

export const paymentLabels: Record<PaymentStatus, string> = { awaiting_checkout: 'Awaiting checkout', pending: 'Pending verification', paid: 'Paid', failed: 'Failed', cancelled: 'Cancelled', expired: 'Expired', refunded: 'Refunded', disputed: 'Disputed' };
const statusCopy: Record<PaymentStatus, string> = { awaiting_checkout: 'The amount is confirmed. A simulated checkout is ready.', pending: 'Checkout does not prove payment. This sample is awaiting a simulated verification result.', paid: 'This is a simulated verified-payment example. No money was moved.', failed: 'This simulated attempt failed. A retry needs a fresh amount and recipient confirmation.', cancelled: 'This simulated checkout was cancelled. No payment is implied.', expired: 'This simulated checkout expired. Confirm a fresh attempt if you want to continue.', refunded: 'This is a simulated refunded-payment example. It is separate from paid.', disputed: 'This is a simulated disputed-payment example. It needs review and is separate from paid.' };
export function PaymentBadge({ status }: { status: PaymentStatus }) { return <Badge tone={status === 'paid' ? 'success' : status === 'failed' ? 'danger' : status === 'pending' || status === 'disputed' ? 'warning' : 'neutral'}>{paymentLabels[status]}</Badge>; }
export function PaymentCard({ payment, details = true }: { payment: PaymentIntent; details?: boolean }) {
  const character = characters.find(c => c.id === payment.characterId);
  return <div className="payment-card stack"><div className="receipt-heading"><Badge>Simulated payment</Badge><PaymentBadge status={payment.status} /></div><strong className="receipt-amount tabular">{formatNaira(payment.amountMinor)} <span>NGN</span></strong><p className="supporting">Received by TalkingStage’s operator.</p><p className="caption muted">Voluntary gift · {character?.name ?? 'Fictional character'} association · no romantic response or photo access is purchased.</p><p className="caption muted tabular">Reference: {payment.reference}</p>{details && <Link href={`/payments/${payment.id}`} className="button button--secondary">View payment details</Link>}</div>;
}
export function GiftDialog({ conversationId, onClose }: { conversationId: string; onClose: () => void }) {
  const c = readConversation(conversationId); const character = characters.find(p => p.id === c?.characterId); const [amount, setAmount] = useState(''); const [step, setStep] = useState<'amount' | 'confirm' | 'created'>('amount'); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [scenario, setScenario] = useState<SpaceScenario>('ready'); const [payment, setPayment] = useState<PaymentIntent | null>(null); const operation = useRef(crypto.randomUUID()); const confirmation = useRef<string | null>(null);
  const minor = parseNaira(amount);
  function next() { setError(''); if (minor === null) { setError('Enter a positive NGN amount using up to two decimal places.'); return; } setStep('confirm'); }
  async function create() { if (busy || minor === null) return; setBusy(true); setError(''); if (!confirmation.current) { const result = confirmGift(conversationId, minor, operation.current); if (result.error) { setError(result.error.message); setBusy(false); return; } confirmation.current = result.data; } const r = await createGift(confirmation.current, scenario); setBusy(false); if (r.error) setError(r.error.message); else { setPayment(r.data); setStep('created'); } }
  return <Overlay open onClose={() => { if (!busy) onClose(); }} title={step === 'created' ? 'Simulated checkout created' : step === 'confirm' ? 'Confirm your voluntary gift' : 'Choose an amount'} description="Frontend simulation only. No card details, money or real checkout links are used." sheet footer={step === 'amount' ? <><Button variant="secondary" onClick={onClose}>Not now</Button><Button onClick={next}>Review amount</Button></> : step === 'confirm' ? <><Button variant="secondary" disabled={busy} onClick={onClose}>Not now</Button><Button variant="quiet" disabled={busy} onClick={() => { confirmation.current = null; operation.current = crypto.randomUUID(); setStep('amount'); }}>Change amount</Button><Button loading={busy} onClick={create}>Confirm {minor === null ? 'amount' : formatNaira(minor)}</Button></> : <Button onClick={onClose}>Done</Button>}><div className="stack">{step === 'amount' ? <><TextField label="Amount in NGN" value={amount} onChange={e => setAmount(e.target.value)} inputMode="decimal" placeholder="Enter your chosen amount" autoComplete="off" /><p className="supporting muted">No amount is preselected. Giving is optional, and you can keep chatting without giving.</p></> : step === 'confirm' ? <div className="receipt-summary stack"><strong className="receipt-amount tabular">{minor === null ? '—' : formatNaira(minor)} <span>NGN</span></strong><dl className="receipt-fields"><div><dt>Recipient</dt><dd>TalkingStage’s operator</dd></div><div><dt>Purpose</dt><dd>Voluntary gift</dd></div><div><dt>Character association</dt><dd>{character?.name ?? 'Unavailable'}</dd></div></dl><p className="supporting">This does not buy affection, a romantic response, messages or photo access.</p><p className="caption muted">Amount limits and the payment provider remain undecided. This preview cannot accept money.</p></div> : payment && <PaymentCard payment={payment} />}{error && <Notice live title="Gift not created" tone="danger">{error}</Notice>}{step !== 'created' && <SpaceReview value={scenario} onChange={setScenario} />}</div></Overlay>;
}
export function PaymentHistory() { return <SpacePage><HistoryContent /></SpacePage>; }
function HistoryContent() {
  const space = usePersonalSpace(); const [filter, setFilter] = useState('all'); const [count, setCount] = useState(5); const payments = paymentHistory().filter(p => filter === 'all' || p.status === filter);
  return <><SpaceBack title="Payment history" /><Notice title="Simulated payment history">These are disposable examples. No real money has been moved.</Notice><SelectField label="Payment status" value={filter} onChange={e => { setFilter(e.target.value); setCount(5); }}><option value="all">All statuses</option>{Object.entries(paymentLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</SelectField>{!space.loaded ? <Skeleton height={160} /> : space.error ? <Notice title="History unavailable" tone="danger">{space.error}<Button onClick={space.retry}>Try again</Button></Notice> : payments.length ? <><div className="payment-history-list">{payments.slice(0, count).map(p => <Link key={p.id} href={`/payments/${p.id}`} className="payment-history-row"><div><strong className="tabular">{formatNaira(p.amountMinor)}</strong><p className="caption muted">{characters.find(c => c.id === p.characterId)?.name} · {new Date(p.createdAt).toLocaleDateString('en-NG')}</p><p className="caption muted tabular">{p.reference}</p></div><PaymentBadge status={p.status} /></Link>)}</div>{count < payments.length && <Button variant="secondary" onClick={() => setCount(v => v + 5)}>Load more payments</Button>}</> : <EmptyState title="No payments here">Voluntary gifts you confirm will appear here. Giving is always optional.</EmptyState>}</>;
}
export function PaymentDetail({ id }: { id: string }) { return <SpacePage><DetailContent id={id} /></SpacePage>; }
function DetailContent({ id }: { id: string }) {
  const space = usePersonalSpace(); const p = paymentById(id); const [scenario, setScenario] = useState<SpaceScenario>('ready'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [gift, setGift] = useState(false);
  async function checkout() { setBusy(true); setError(''); const r = await simulateCheckout(id, scenario); setBusy(false); if (r.error) setError(r.error.message); }
  return <><Link href="/settings/payments" className="profile-back">Back to payment history</Link><h1 className="display page-title">Payment details</h1>{!space.loaded ? <Skeleton height={260} /> : space.error ? <Notice title="Payment unavailable" tone="danger">{space.error}<Button onClick={space.retry}>Try again</Button></Notice> : !p ? <EmptyState title="Payment not found">This payment is unavailable or doesn’t belong to this demo account.</EmptyState> : <><PaymentCard payment={p} details={false} /><Notice title={`Simulated · ${paymentLabels[p.status]}`}>{statusCopy[p.status]}</Notice><dl className="receipt-fields"><div><dt>Created</dt><dd>{new Date(p.createdAt).toLocaleString('en-NG', { timeZone: 'Africa/Lagos' })}</dd></div><div><dt>Currency</dt><dd>NGN</dd></div><div><dt>Verification</dt><dd>{p.verifiedAt ? 'Simulated result only' : 'No verified result'}</dd></div></dl>{p.status === 'awaiting_checkout' && <Button loading={busy} onClick={checkout}>Simulate checkout</Button>}{['failed', 'cancelled', 'expired'].includes(p.status) && (readConversation(p.conversationId) ? <Button onClick={() => setGift(true)}>Review a new attempt</Button> : <p className="supporting muted">The associated conversation has been deleted. This payment record remains visible.</p>)}{p.status === 'pending' && <Button variant="secondary" loading={busy} onClick={async () => { setBusy(true); const r = await loadSpace(scenario); setBusy(false); setError(r.error?.message ?? ''); }}>Check simulated status</Button>}<Link href="/support">Payment support information</Link>{error && <Notice live title="Payment action unavailable" tone="danger">{error} The last known payment status is unchanged.</Notice>}<SpaceReview value={scenario} onChange={setScenario} />{process.env.NODE_ENV === 'development' && <details className="discovery-qa"><summary>Payment review controls</summary><SelectField label="Simulated payment outcome" value={p.status} onChange={e => reviewPaymentStatus(p.id, e.target.value as PaymentStatus)}>{Object.entries(paymentLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</SelectField></details>}{gift && <GiftDialog conversationId={p.conversationId} onClose={() => setGift(false)} />}</>}</>;
}
