"use client";
import Link from 'next/link';
import { useEffect, useState, useSyncExternalStore, type ReactNode } from 'react';
import { useRouter } from 'next/navigation';
import type { Gender, Language, Memory } from '@/lib/contracts';
import { characters } from '@/lib/mock/discovery';
import { deleteMemory, deleteMockAccount, loadSpace, memoryState, saveMemoryEnabled, savePreferences, saveRequests, saveSampleMemory, serverSpaceVersion, spaceVersion, subscribeSpace, type SpaceScenario } from '@/lib/mock/personal-space';
import { useMockAccount } from './account-provider';
import { UserBoundary } from './user-boundary';
import { CharacterPhoto } from './discovery';
import { Badge, Button, Card, Checkbox, Chip, EmptyState, Notice, SelectField, Skeleton, Switch, TextField } from './ui/primitives';
import { Overlay } from './ui/overlay';
import { Icon } from './ui/icon';

export function usePersonalSpace() {
  const revision = useSyncExternalStore(subscribeSpace, spaceVersion, serverSpaceVersion); const [loaded, setLoaded] = useState(false); const [error, setError] = useState(''); const [attempt, setAttempt] = useState(0);
  useEffect(() => { let current = true; loadSpace().then(r => { if (current) { setError(r.error?.message ?? ''); setLoaded(true); } }); return () => { current = false; }; }, [attempt]);
  return { revision, loaded, error, retry: () => { setLoaded(false); setAttempt(v => v + 1); } };
}
export function SpacePage({ children }: { children: ReactNode }) { return <UserBoundary active="Settings"><div className="space-page stack">{children}</div></UserBoundary>; }
export function SpaceBack({ title }: { title: string }) { return <><Link className="profile-back" href="/settings"><Icon name="back" />Back to settings</Link><h1 className="display page-title">{title}</h1></>; }
export function SpaceReview({ value, onChange }: { value: SpaceScenario; onChange: (s: SpaceScenario) => void }) { return process.env.NODE_ENV === 'development' ? <details className="discovery-qa"><summary>Personal-space review controls</summary><SelectField label="Save scenario" value={value} onChange={e => onChange(e.target.value as SpaceScenario)}>{['ready', 'offline', 'error'].map(s => <option key={s}>{s}</option>)}</SelectField></details> : null; }
export function Settings() { return <SpacePage><SettingsContent /></SpacePage>; }
function SettingsContent() {
  const { user } = useMockAccount();
  const links = [{ title: 'Preferences', text: 'Your name, character preferences and language.', href: '/settings/preferences', icon: 'people' as const }, { title: 'Memories', text: 'Choose what each character can remember.', href: '/settings/memories', icon: 'message' as const }, { title: 'Monetary requests', text: 'Your choice, with no pressure to give.', href: '/settings/requests', icon: 'shield' as const }, { title: 'Payment history', text: 'Amounts, references and status in one place.', href: '/settings/payments', icon: 'payment' as const }];
  return <><header className="stack"><p className="supporting muted">Your space, {user?.displayName}.</p><h1 className="display page-title">Settings</h1><p className="muted">Keep the experience comfortable for you.</p></header><div className="settings-grid">{links.map(item => <Link className="setting-link" key={item.href} href={item.href}><span className="setting-link__icon"><Icon name={item.icon} /></span><div><h2>{item.title}</h2><p className="supporting muted">{item.text}</p></div><Icon name="arrow" /></Link>)}</div><Card><div className="stack"><h2>Access and notifications</h2><p className="supporting muted">This preview uses your completed adult onboarding. Adult access uses your 18+ checkbox declaration; it does not independently verify age. There are no email or push reminders in the launch frontend.</p><div className="row"><Link href="/privacy">Privacy information</Link><Link href="/support">Support</Link></div></div></Card><div className="account-danger"><h2>Account and data</h2><p className="supporting muted">Review what deletion removes before making a choice.</p><Link href="/settings/account" className="button button--danger">Delete account</Link></div></>;
}
export function Preferences() { return <SpacePage><PreferencesContent /></SpacePage>; }
function PreferencesContent() {
  const { user } = useMockAccount(); const [name, setName] = useState(user?.displayName ?? ''); const [genders, setGenders] = useState<Gender[]>(user?.preferences.characterGenders ?? []); const [language, setLanguage] = useState<Language>(user?.preferences.language ?? 'english'); const [scenario, setScenario] = useState<SpaceScenario>('ready'); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [saved, setSaved] = useState(false);
  const dirty = name !== user?.displayName || genders.join() !== user?.preferences.characterGenders.join() || language !== user?.preferences.language;
  async function save() { if (busy) return; setBusy(true); setError(''); setSaved(false); const r = await savePreferences(name, { characterGenders: genders, language }, scenario); setBusy(false); if (r.error) setError(r.error.message); else setSaved(true); }
  return <><SpaceBack title="Preferences" /><p className="muted">These preferences guide discovery and conversation language.</p><Card><form className="stack" onSubmit={e => { e.preventDefault(); void save(); }}><TextField label="Preferred name" value={name} maxLength={60} onChange={e => { setName(e.target.value); setSaved(false); }} autoComplete="nickname" /><fieldset className="space-fieldset"><legend>Characters you’d like to discover</legend><div className="row">{(['woman', 'man'] as const).map(g => <Chip key={g} selected={genders.includes(g)} onClick={() => { setGenders(current => current.includes(g) ? current.filter(item => item !== g) : [...current, g]); setSaved(false); }}>{g === 'woman' ? 'Women' : 'Men'}</Chip>)}</div></fieldset><SelectField label="Conversation language" value={language} onChange={e => { setLanguage(e.target.value as Language); setSaved(false); }}><option value="english">English</option><option value="english_pidgin">English with Pidgin</option></SelectField>{error && <Notice live title="Preferences not saved" tone="danger">{error}</Notice>}{saved && <Notice live title="Preferences saved" tone="success">Your choices are updated.</Notice>}<Button type="submit" loading={busy} disabled={!dirty}>Save preferences</Button></form></Card><SpaceReview value={scenario} onChange={setScenario} /></>;
}
export function RequestSettings() { return <SpacePage><RequestContent /></SpacePage>; }
function RequestContent() {
  const { user } = useMockAccount(); const [enabled, setEnabled] = useState(user?.allowMonetaryRequests ?? false); const [scenario, setScenario] = useState<SpaceScenario>('ready'); const [busy, setBusy] = useState(false); const [feedback, setFeedback] = useState(''); const [error, setError] = useState('');
  async function save() { setBusy(true); setError(''); setFeedback(''); const r = await saveRequests(enabled, scenario); setBusy(false); if (r.error) setError(r.error.message); else setFeedback(enabled ? 'Monetary requests enabled.' : 'Monetary requests muted.'); }
  return <><SpaceBack title="Monetary requests" /><p className="muted">Giving is optional. Your conversation and romantic pace do not depend on payment.</p><Card><div className="stack"><Switch label="Allow characters to make monetary requests" hint="Turn this off to stop character-initiated requests. You can still choose to give voluntarily." checked={enabled} onChange={e => { setEnabled(e.target.checked); setFeedback(''); }} /><p className="supporting muted">You can decline or ignore a request. A refusal never changes affection, photo access or the tone of the conversation. Requests are not made during early conversations.</p><Notice title="Who receives the money?">Received by TalkingStage’s operator. The fictional character cannot receive money.</Notice>{error && <Notice live title="Setting not saved" tone="danger">{error}</Notice>}{feedback && <Notice live title="Request setting saved" tone="success">{feedback}</Notice>}<Button loading={busy} disabled={enabled === user?.allowMonetaryRequests} onClick={save}>Save request setting</Button></div></Card><SpaceReview value={scenario} onChange={setScenario} /></>;
}
export function Memories({ characterId }: { characterId?: string }) { return <SpacePage><MemoryContent characterId={characterId} /></SpacePage>; }
function MemoryContent({ characterId }: { characterId?: string }) {
  const space = usePersonalSpace(); const c = characters.find(c => c.id === characterId); const [scenario, setScenario] = useState<SpaceScenario>('ready'); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [dialog, setDialog] = useState<'ordinary' | 'sensitive' | null>(null); const [consent, setConsent] = useState(false); const [deleting, setDeleting] = useState<Memory | null>(null); const [inspecting, setInspecting] = useState<Memory | null>(null);
  const memory = c ? memoryState(c.id) : null;
  async function toggle(enabled: boolean) { if (!c) return; setBusy(true); setError(''); const r = await saveMemoryEnabled(c.id, enabled, scenario); setBusy(false); if (r.error) setError(r.error.message); }
  async function saveSample() { if (!c || !dialog) return; setBusy(true); setError(''); const r = await saveSampleMemory(c.id, dialog === 'sensitive', consent, scenario); setBusy(false); if (r.error) setError(r.error.message); else setDialog(null); }
  async function remove() { if (!deleting) return; setBusy(true); setError(''); const r = await deleteMemory(deleting.id, scenario); setBusy(false); if (r.error) setError(r.error.message); else setDeleting(null); }
  return <><SpaceBack title={c ? `Memories with ${c.name}` : 'Memories'} /><p className="muted">Facts stay separate for each character. Sensitive details need your explicit consent. Disable memory to stop saving and using facts; existing facts stay visible until you delete them.</p>{!space.loaded ? <div role="status" aria-label="Loading memories"><Skeleton height={120} /></div> : space.error ? <Notice title="Memories unavailable" tone="danger">{space.error}<Button onClick={space.retry}>Try again</Button></Notice> : characterId && !c ? <EmptyState title="Character not found" action={<Link href="/settings/memories">Explore memories</Link>}>Choose a character from your memory list.</EmptyState> : !c ? <div className="memory-character-list">{characters.map(character => { const data = memoryState(character.id); return <Link className="memory-character" href={`/settings/memories/${character.id}`} key={character.id}><span className="conversation-avatar"><CharacterPhoto character={character} retryable={false} /></span><span><strong>{character.name}</strong><span className="caption muted">{data.items.length} saved {data.items.length === 1 ? 'fact' : 'facts'} · Memory {data.enabled ? 'enabled' : 'disabled'}</span></span><Icon name="arrow" /></Link>; })}</div> : memory && <><Card><Switch label={`Enable memory for ${c.name}`} hint="Your permission applies to this character only. You can withdraw it at any time." checked={memory.enabled} disabled={busy} onChange={e => toggle(e.target.checked)} /></Card>{!memory.enabled && <Notice title="Memory disabled">These facts are not used for future context or new saves. Deleting facts also removes them from future memory context.</Notice>}{memory.items.length ? <div className="stack">{memory.items.map(m => <Card key={m.id}><div className="stack"><p>{m.content}</p><span className="caption muted">Saved with explicit permission · {new Date(m.savedAt).toLocaleDateString('en-NG')}</span><div className="row"><Button variant="quiet" onClick={() => setInspecting(m)}>Inspect memory</Button><Button variant="danger" onClick={() => setDeleting(m)}>Delete memory</Button></div></div></Card>)}</div> : <EmptyState title="No saved facts here">Enable memory and use a sample below to review saving and consent. This preview never extracts facts from your written messages.</EmptyState>}<div className="row"><Button variant="secondary" disabled={!memory.enabled || busy} onClick={() => { setDialog('ordinary'); setConsent(false); setError(''); }}>Save a sample fact</Button><Button variant="quiet" disabled={!memory.enabled || busy} onClick={() => { setDialog('sensitive'); setConsent(false); setError(''); }}>Review sensitive-memory consent</Button></div></>}{error && !dialog && !deleting && <Notice live title="Memory change not saved" tone="danger">{error}</Notice>}<SpaceReview value={scenario} onChange={setScenario} />
    <Overlay open={!!dialog} onClose={() => { if (!busy) setDialog(null); }} title={dialog === 'sensitive' ? 'Save a sensitive sample?' : 'Remember this sample fact?'} description="This is a fictional demonstration. Saving gives this character permission to use the sample fact in future context." footer={<><Button variant="secondary" disabled={busy} onClick={() => setDialog(null)}>Not now</Button><Button loading={busy} disabled={dialog === 'sensitive' && !consent} onClick={saveSample}>Save sample memory</Button></>}><div className="stack"><p>{dialog === 'sensitive' ? 'A sample health detail (fictional demonstration only).' : c ? `Enjoys ${c.interests[0]}. (Sample fact)` : ''}</p>{dialog === 'sensitive' && <Checkbox label="I explicitly allow this character to save and use this sensitive sample." checked={consent} onChange={e => setConsent(e.target.checked)} />}{error && <Notice live title="Memory not saved" tone="danger">{error}</Notice>}</div></Overlay>
    <Overlay open={!!deleting} onClose={() => { if (!busy) setDeleting(null); }} title="Delete this memory?" description="This fact will be removed from the list and future memory context. The conversation and other characters’ memories are unchanged." footer={<><Button variant="secondary" disabled={busy} onClick={() => setDeleting(null)}>Keep memory</Button><Button variant="danger" loading={busy} onClick={remove}>Delete memory</Button></>}><p>{deleting?.content}</p>{error && <Notice live title="Memory not deleted" tone="danger">{error}</Notice>}</Overlay>
    <Overlay open={!!inspecting} onClose={() => setInspecting(null)} title="Memory details"><div className="stack"><p>{inspecting?.content}</p><Badge>Explicit consent</Badge><p className="supporting muted">Source: reviewer-selected synthetic sample. No original message or sensitive personal text was stored. Deleting this fact prevents future context use.</p></div></Overlay>
  </>;
}
export function AccountDeletion() { return <SpacePage><AccountDeletionContent /></SpacePage>; }
function AccountDeletionContent() {
  const router = useRouter(); const [text, setText] = useState(''); const [scenario, setScenario] = useState<SpaceScenario>('ready'); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [open, setOpen] = useState(false);
  async function remove() { setBusy(true); setError(''); const r = await deleteMockAccount(text, scenario); setBusy(false); if (r.error) setError(r.error.message); else router.replace('/account-deleted'); }
  return <><SpaceBack title="Delete account" /><Card><div className="stack"><h2>Review what happens</h2><p>Account deletion removes your profile, conversations, saved memories and access to the account.</p><p className="supporting muted">In a real service, necessary transaction and legal records may be retained for reconciliation and legal obligations. Final retention periods and exceptions are still awaiting policy review.</p><Notice title="Frontend simulation">This action clears disposable account/chat/memory/payment/report fixtures in this browser session. There are no real account or transaction records to delete.</Notice><Button variant="danger" onClick={() => setOpen(true)}>Review account deletion</Button></div></Card><SpaceReview value={scenario} onChange={setScenario} /><Overlay open={open} onClose={() => { if (!busy) setOpen(false); }} title="Delete your demo account?" description="All disposable preview data will be cleared and you will be signed out. This cannot be undone in this session." footer={<><Button variant="secondary" disabled={busy} onClick={() => setOpen(false)}>Keep account</Button><Button variant="danger" loading={busy} disabled={text !== 'DELETE'} onClick={remove}>Delete demo account</Button></>}><div className="stack"><TextField label="Type DELETE to confirm" value={text} onChange={e => setText(e.target.value)} autoComplete="off" />{error && <Notice live title="Account not deleted" tone="danger">{error}</Notice>}</div></Overlay></>;
}
