"use client";
import { useId, type ButtonHTMLAttributes, type InputHTMLAttributes, type ReactNode, type SelectHTMLAttributes, type TextareaHTMLAttributes } from "react";
import { Icon, type IconName } from "./icon";
export function Button({ variant = "primary", loading = false, children, className = "", disabled, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "quiet" | "danger"; loading?: boolean }) { return <button type="button" {...props} className={`button button--${variant} ${className}`} disabled={disabled || loading} aria-busy={loading || undefined}>{loading && <span className="spinner" aria-hidden="true" />}{children}</button>; }
export function IconButton({ label, icon, ...props }: Omit<ButtonHTMLAttributes<HTMLButtonElement>, "children" | "aria-label"> & { label: string; icon: IconName }) { return <Button {...props} variant="quiet" className="button--icon" aria-label={label}><Icon name={icon} /></Button>; }
type FieldMeta = { label: string; hint?: string; error?: string };
function FieldFrame({ id, label, hint, error, children }: FieldMeta & { id: string; children: ReactNode }) { return <div className="field"><label className="field__label" htmlFor={id}>{label}</label>{children}{hint && <p className="field__hint" id={`${id}-hint`}>{hint}</p>}{error && <p className="field__error" id={`${id}-error`}><Icon name="warning" />{error}</p>}</div>; }
function describedBy(id: string, hint?: string, error?: string, external?: string) { return [hint && `${id}-hint`, error && `${id}-error`, external].filter(Boolean).join(" ") || undefined; }
export function TextField({ label, hint, error, id: providedId, ...props }: InputHTMLAttributes<HTMLInputElement> & FieldMeta) { const generatedId = useId(); const id = providedId ?? generatedId; return <FieldFrame {...{ id, label, hint, error }}><input {...props} id={id} className={`field__control ${props.className ?? ""}`} aria-invalid={!!error || undefined} aria-describedby={describedBy(id, hint, error, props["aria-describedby"])} /></FieldFrame>; }
export function TextArea({ label, hint, error, id: providedId, ...props }: TextareaHTMLAttributes<HTMLTextAreaElement> & FieldMeta) { const generatedId = useId(); const id = providedId ?? generatedId; return <FieldFrame {...{ id, label, hint, error }}><textarea {...props} id={id} className={`field__control ${props.className ?? ""}`} aria-invalid={!!error || undefined} aria-describedby={describedBy(id, hint, error, props["aria-describedby"])} /></FieldFrame>; }
export function SelectField({ label, hint, error, id: providedId, children, ...props }: SelectHTMLAttributes<HTMLSelectElement> & FieldMeta) { const generatedId = useId(); const id = providedId ?? generatedId; return <FieldFrame {...{ id, label, hint, error }}><select {...props} id={id} className={`field__control ${props.className ?? ""}`} aria-invalid={!!error || undefined} aria-describedby={describedBy(id, hint, error, props["aria-describedby"])}>{children}</select></FieldFrame>; }
export function Switch({ label, hint, id: providedId, ...props }: Omit<InputHTMLAttributes<HTMLInputElement>, "type"> & { label: string; hint?: string }) { const generatedId = useId(); const id = providedId ?? generatedId; return <label className="switch" htmlFor={id}><span><span className="field__label">{label}</span>{hint && <span className="field__hint" id={`${id}-hint`} style={{ display: "block", marginTop: 4 }}>{hint}</span>}</span><input {...props} id={id} type="checkbox" role="switch" className="switch__input" aria-describedby={describedBy(id, hint, undefined, props["aria-describedby"])} /></label>; }
export function Checkbox({ label, ...props }: Omit<InputHTMLAttributes<HTMLInputElement>, "type"> & { label: string }) { return <label className="choice"><input {...props} type="checkbox" /><span className="supporting">{label}</span></label>; }
export function Chip({ selected, children, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { selected: boolean }) { return <button type="button" {...props} className="chip" aria-pressed={selected}>{selected && <Icon name="check" />}{children}</button>; }
export type Tone = "neutral" | "success" | "warning" | "danger";
export function Badge({ children, tone }: { children: ReactNode; tone?: Tone }) { return <span className={`badge${tone ? ` badge--${tone}` : ""}`}>{children}</span>; }
export function Notice({ title, children, tone = "neutral", live = false }: { title: string; children?: ReactNode; tone?: Tone; live?: boolean }) { return <div className={`notice${tone === "neutral" ? "" : ` notice--${tone}`}`} role={live ? (tone === "danger" ? "alert" : "status") : undefined}><Icon name={tone === "success" ? "check" : tone === "warning" || tone === "danger" ? "warning" : "info"} /><div className="notice__body"><strong className="supporting">{title}</strong>{children && <div className="supporting">{children}</div>}</div></div>; }
export function Skeleton({ width = "100%", height = 20 }: { width?: string | number; height?: number }) { return <span aria-hidden="true" className="skeleton" style={{ width, height }} />; }
export function Card({ children, className = "" }: { children: ReactNode; className?: string }) { return <div className={`card ${className}`}>{children}</div>; }
export function EmptyState({ title, children, action, icon = "message" }: { title: string; children: ReactNode; action?: ReactNode; icon?: IconName }) { return <div className="empty-state"><span className="empty-state__icon"><Icon name={icon} /></span><h3>{title}</h3><p>{children}</p>{action}</div>; }
